# Generated by Django 2.2.3 on 2019-09-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190829_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_tble',
            old_name='BillBoardId',
            new_name='boardId',
        ),
    ]
