# Generated by Django 2.2.3 on 2019-09-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190902_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_tble',
            old_name='City',
            new_name='number',
        ),
    ]
