# Generated by Django 2.2.3 on 2019-07-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardId', models.CharField(max_length=20)),
                ('imglink', models.ImageField(upload_to='board_pics')),
                ('facingDirection', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('place', models.CharField(max_length=100)),
                ('sqfeetSize', models.IntegerField()),
                ('backLight', models.BooleanField()),
                ('available', models.BooleanField()),
            ],
        ),
    ]
