# Generated by Django 2.2.3 on 2019-07-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='boardId',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
