# Generated by Django 2.2.3 on 2019-07-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190716_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billboard',
            old_name='place',
            new_name='city',
        ),
    ]
