# Generated by Django 2.2.3 on 2019-07-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190717_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='facingDirection',
            field=models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], default='North', max_length=50),
        ),
    ]
